### ISSUE TITLE
有时不能全部展开

### ISSUE THREAD

**Issue by maxli** [lisiyizu/vue-ztree-2.0#1]
你好! 
我正在尝试使用的的控件。首先非常感谢！
我的tree一共又4级。使用控件时发现，有时只能显示2级，有时3级，有时可以4级全部显示。看了log，4级的数据都已经有了。因为刚刚开始使用vue，不是很熟，希望能给我一些解决这个问题的思路。或者能亲自解决一下。 再一次表示感谢！

**Comment by maxli** [comment]
你好，补充些信息。好像出现了无限循环。100次后vue强行结束循环。
log
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "list" 
(found in <VueZtree> at D:\dev\faceManage\src\components\vue-ztree.vue)
[Vue warn]: You may have an infinite update loop in watcher with expression "list" 
(found in <VueZtree> at D:\dev\faceManage\src\components\vue-ztree.vue)

**Comment by lisiyizu** [comment]
已经修复了，你再获取我的版本试试

**Comment by maxli** [comment]
你好！很感谢你的快速反馈！新版本我试了一下，那儿死循环的问题的确没有了。可是，现在还支持数据绑定吗？我现在点击一个节点，动态请求改节点下面的子节点，能看到数据已经更新，但新的子节点不显示。

**Comment by lisiyizu** [comment]
我改了改，模拟了动态加载节点的情况，你试试。

**Comment by gevilhost** [comment]
我想问一下您这个如果节点上加一个右键菜单要咋做呢

**Comment by maxli** [comment]
好用了。非常感谢。
