### ISSUE TITLE
异步加载展开菜单报错

### ISSUE THREAD

**Issue by commitqdy** [lisiyizu/vue-ztree-2.0#16]
![bug](https://user-images.githubusercontent.com/24648359/34806642-2ed1a268-f6bf-11e7-9687-5da495ef2516.png)
异步加载点击按钮总是报Cannot read property 'length' of undefined"，虽然不影响使用，但看着好难受，有没有知道怎么解决的？

**Comment by lisiyizu** [comment]
![image](https://user-images.githubusercontent.com/12014252/34866187-9e620d6e-f7b6-11e7-98a8-b12e5c1daa54.png)
已经解决了
