### ISSUE TITLE
怎样在自己的项目中运用这个文件树功能

### ISSUE THREAD

**Issue by zhuyinjing** [lisiyizu/vue-ztree-2.0#17]
作者您好，
我想要在我的vue项目中 用您这个文件树的 功能，
我怎样用到我项目里呢？
新手求教～
谢谢！

**Comment by zhuyinjing** [comment]
在项目里 引入  vue-ztree.vue 对吗？
还有别的方法吗？比如说 npm install 然后 import

**Comment by lisiyizu** [comment]
直接复制源码

**Comment by zhuyinjing** [comment]
thanks
