### ISSUE TITLE
有2.0的npm安装吗

### ISSUE THREAD

**Issue by lxmbetterman** [lisiyizu/vue-ztree-2.0#22]
敢问大神 2.0版本没有提供npm下载吗 @lisiyizu

**Comment by lisiyizu** [comment]
目前省事没做，谢谢你的建议

**Comment by caiweiming123** [comment]
建议加上npm构建会方便一些，而且这个东西写得不错

**Comment by lisiyizu** [comment]
今天发布到npm了，感谢支持～
地址：https://www.npmjs.com/package/vue-ztree-2.0

**Comment by lisiyizu** [comment]
已经支持了～
