### ISSUE TITLE
vue-cli 3.0 下面， 会报错 

### ISSUE THREAD

**Issue by OSganping** [lisiyizu/vue-ztree-2.0#24]
`[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
`

**Comment by lisiyizu** [comment]
今天发布到npm了，感谢支持～
地址：https://www.npmjs.com/package/vue-ztree-2.0

**Comment by zengxiaoling** [comment]
还是出现这个问题

**Comment by lisiyizu** [comment]
请问使用的 vue-cli 3.0 吗？
![image](https://user-images.githubusercontent.com/12014252/49004403-28b75e00-f19f-11e8-96c6-384f98a6aae1.png)

**Comment by zengxiaoling** [comment]
是用的nuxt，还有个问题 如果数据嵌套层级有差不多7层，且每层数据量大致有一百多个，页面会卡顿吗？

**Comment by lisiyizu** [comment]
哈哈哈，这么大的量吗？你试试

**Comment by zengxiaoling** [comment]
加了上面的代码，还是会报错

**Comment by lisiyizu** [comment]
额，那就不晓得少情况了
